AWSTemplateFormatVersion: 2010-09-09
Description: The AWS CloudFormation template for Kinesis Stream
Parameters:
  Environment:
    Description: 'Environment'
    Type: String
    MinLength: '3'
    MaxLength: '5'
Resources:
  KinesisStream:
    Type: 'AWS::Kinesis::Stream'
    Properties:
      Name: !Join 
        - ''
        - - kinesis-fh-s3
          - !Ref Environment
      RetentionPeriodHours: 24
      ShardCount: 2
      Tags:
        - Key: Environment
          Value: !Ref Environment
        - Key: Project
          Value: DemoKinesis
  KinesisFirehoseDeliveryStream:
    Type: 'AWS::KinesisFirehose::DeliveryStream'
    Properties:
      DeliveryStreamName: !Join 
        - ''
        - - kinesis-fh-s3
          - !Ref Environment
      DeliveryStreamType: DirectPut
      S3DestinationConfiguration:
        BucketARN: 'arn:aws:s3:::apps.recommendation.dev.eu-central-1'
        Prefix: 'events/'
        BufferingHints:
          IntervalInSeconds: 60
          SizeInMBs: 100
        CloudWatchLoggingOptions:
          Enabled: 'true'
          LogGroupName: firehose-s3
          LogStreamName: demo-firehose-s3
        CompressionFormat: GZIP
        EncryptionConfiguration:
          KMSEncryptionConfig: 
            AWSKMSKeyARN: 'arn:aws:kms:eu-central-1:569900110365:key/3d85d6dc-5ba4-40d2-ba32-1d81ccda1252'
        RoleARN: !GetAtt 
          - FirehoseDeliveryIAMRole
          - Arn
    DependsOn:
      - FirehoseDeliveryIAMPolicy
  FirehoseDeliveryIAMRole:
    Type: 'AWS::IAM::Role'
    Properties:
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Sid: ''
            Effect: Allow
            Principal:
              Service: firehose.amazonaws.com
            Action: 'sts:AssumeRole'
  FirehoseDeliveryIAMPolicy:
    Type: 'AWS::IAM::Policy'
    Properties:
      PolicyName: !Join 
        - ''
        - - kinesis-fh-s3
          - !Ref Environment
      PolicyDocument:
        Version: 2012-10-17
        Statement:
        - Sid: 'gluetableread'
          Effect: Allow
          Action:
            - 'glue:GetTableVersions'
          Resource: '*'          
        - Sid: 's3access'  
          Effect: Allow
          Action:
            - 's3:AbortMultipartUpload'
            - 's3:GetBucketLocation'
            - 's3:GetObject'
            - 's3:ListBucket'
            - 's3:ListBucketMultipartUploads'
            - 's3:PutObject'
          Resource:
            - 'arn:aws:s3:::apps.recommendation.dev.eu-central-1'
            - 'arn:aws:s3:::s3://apps.recommendation.dev.eu-central-1/*'
        - Sid: 'kmsperm'
          Effect: Allow
          Action:
            - 'kms:GenerateDataKey'
            - 'kms:Decrypt'
          Resource:
            - 'arn:aws:kms:eu-central-1:569900110365:key/3d85d6dc-5ba4-40d2-ba32-1d81ccda1252'    
        - Sid: 'lambdaperm'
          Effect: Allow
          Action:
            - 'lambda:InvokeFunction'
            - 'lambda:GetFunctionConfiguration'
          Resource:
            - 'arn:aws:lambda:eu-central-1:569900110365:function:%FIREHOSE_DEFAULT_FUNCTION%:%FIREHOSE_DEFAULT_VERSION%'                          
          Condition:
            StringEquals:
              'kms:ViaService': s3.eu-central-1.amazonaws.com
            StringLike:
              'kms:EncryptionContext:aws:s3:arn':
                - 'arn:aws:s3:::apps.recommendation.dev.eu-central-1/events/*'
        - Sid: 'LogPerm'  
          Effect: Allow
          Action:
            - 'logs:PutLogEvents'
          Resource:
            - 'arn:aws:logs:eu-central-1:569900110365:log-group:/aws/*/*:log-stream:*'
        - Sid: 'kinesisPerm'  
          Effect: Allow
          Action:
            - 'kinesis:DescribeStream'
            - 'kinesis:GetShardIterator'
            - 'kinesis:GetRecords'
          Resource: !GetAtt 
            - KinesisStream
            - Arn
      Roles:
        - !Ref FirehoseDeliveryIAMRole
    DependsOn:
      - KinesisStream
Outputs:
  kinesisStreamArn:
    Description: Kinesis Stream ARN
    Value: !GetAtt 
      - KinesisStream
      - Arn
  firehoseDeliveryStreamArn:
    Description: Firehose Delivery Stream ARN
    Value: !GetAtt 
      - KinesisFirehoseDeliveryStream
      - Arn
  firehoseDeliveryRoleArn:
    Description: Firehose Delivery Role ARN
    Value: !GetAtt 
      - FirehoseDeliveryIAMRole
      - Arn
